deploy :
    npx hardhat run ignition/modules/NameFave.ts --network sepolia

compile :
	npx hardhat compile

verify :
	npx hardhat verify --network sepolia 0x16955047994d6B59cfc21A397ed712b9eeE426Ad, 0xDE115676F736F154eEF8398A37e4ACB4d61892e6